CREATE TABLE IF NOT EXISTS hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app     VARCHAR(100)                          NOT NULL,
    uri     VARCHAR(2000)                         NOT NULL,
    ip      INET                                  NOT NULL,
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_app_not_empty CHECK (LENGTH(app) > 0),
    CONSTRAINT chk_uri_not_empty CHECK (LENGTH(uri) > 0)
);

CREATE INDEX IF NOT EXISTS idx_hits_app_created ON hits(app, created);

CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits(ip);

CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits(uri);